# Generated by Django 5.0.6 on 2024-05-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyatidnevka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=20)),
                ('Strih', models.CharField(max_length=20)),
                ('Articul', models.CharField(max_length=20)),
                ('NameTovara', models.CharField(max_length=20)),
                ('BrendTovara', models.CharField(max_length=20)),
                ('Image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('Opisanie', models.CharField(max_length=100)),
            ],
        ),
    ]
